# Simulation Environment Parameters (ROS1 Noetic)

# Initial pose
init_x: 0.0
init_y: 0.0
init_z: 0.0

# Robot model
mesh_resource: "package://simulation_env_ros1/meshes/robot.dae"
mesh_scale: 0.0005
mesh_offset_x: -0.15
mesh_offset_y: -0.16

# Control
max_linear_vel: 1.0
max_angular_vel: 3.14159
control_rate: 50.0

# Point cloud
pcd_file_path: "/home/percy/FSGP-BGK-ROS2/src/simulation_env_ros1/PCD/forest.pcd"
handle_range: 15.0
ground_range: 0.25
voxel_size: 0.05

# Plane fitting
max_tilt_angle: 30.0
inlier_threshold: 0.1
